export const STORE_ACTION_TYPES = {
  UPDATE_LANGUAGE: "UPDATE LANGUAGE",
  GET_LANGUAGE: "GET LANGUAGE",
  START_LOADING: "START LOADING",
  END_LOADING: "END LOADING",
  SET_PROVISIONING: "SET_PROVISIONING",
  SET_WIFI_NETWORKS: "SET_WIFI_NETWORKS",
  RESET_WIFI_NETWORKS: "RESET_WIFI_NETWORKS",
};
